#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.14
# In conjunction with Tcl version 8.6
#    Aug 14, 2018 07:19:28 PM

import sys
import time
import random

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

import Tkinter as tk
import GUI_Design_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root, top
    root = Tk()
    GUI_Design_support.set_Tk_var()
    top = App (root)
    GUI_Design_support.init(root, top)

    # Actualizamos la interfaz en general
    root.mainloop()

w = None
def create_App(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    GUI_Design_support.set_Tk_var()
    top = App (w)
    GUI_Design_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_App():
    global w
    w.destroy()
    w = None


# Creamos la aplicación con la interfaz gráfica
class App:
    def __init__(self, top=None):
        # Variables de funcionamiento del sistema
        self.TimerInterval = 1000

        self.diameterAxisY = 0


        # Variables referentes a la interfaz gráfica
        self.top = top

        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {DejaVu Sans} -size 12 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {DejaVu Sans} -size 11 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {DejaVu Sans} -size 12 -weight bold -slant "  \
            "roman -underline 1 -overstrike 0"

        top.geometry("672x420+376+182")
        top.title("Extrusora de plástico 3DTops")
        top.configure(background="#ffffff")
        top.configure(highlightcolor="black")

        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.04, rely=0.26, relheight=0.54, relwidth=0.45)
        self.Frame1.configure(relief=RIDGE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=RIDGE)
        self.Frame1.configure(background="#ffffff")
        self.Frame1.configure(width=305)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.03, rely=0.18, height=23, width=147)
        self.Label1.configure(activebackground="#ffffff")
        self.Label1.configure(background="#ffffff")
        self.Label1.configure(font=font10)
        self.Label1.configure(text='''Diámetro eje Y ->''')

        self.Label1_2 = Label(self.Frame1)
        self.Label1_2.place(relx=0.03, rely=0.31, height=23, width=147)
        self.Label1_2.configure(activebackground="#ffffff")
        self.Label1_2.configure(background="#ffffff")
        self.Label1_2.configure(font=font10)
        self.Label1_2.configure(text='''Diámetro eje X ->''')

        self.Label1_3 = Label(self.Frame1)
        self.Label1_3.place(relx=0.03, rely=0.44, height=23, width=157)
        self.Label1_3.configure(activebackground="#ffffff")
        self.Label1_3.configure(background="#ffffff")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(text='''Temperatura C1 ->''')

        self.Label1_4 = Label(self.Frame1)
        self.Label1_4.place(relx=0.03, rely=0.58, height=23, width=157)
        self.Label1_4.configure(activebackground="#ffffff")
        self.Label1_4.configure(background="#ffffff")
        self.Label1_4.configure(font=font10)
        self.Label1_4.configure(text='''Temperatura C2 ->''')

        self.Label1_5 = Label(self.Frame1)
        self.Label1_5.place(relx=0.03, rely=0.71, height=23, width=177)
        self.Label1_5.configure(activebackground="#ffffff")
        self.Label1_5.configure(background="#ffffff")
        self.Label1_5.configure(font=font10)
        self.Label1_5.configure(text='''Velocidad Angular ->''')

        self.Label1_6 = Label(self.Frame1)
        self.Label1_6.place(relx=0.03, rely=0.84, height=23, width=197)
        self.Label1_6.configure(activebackground="#ffffff")
        self.Label1_6.configure(background="#ffffff")
        self.Label1_6.configure(font=font10)
        self.Label1_6.configure(text='''Velocidad de tracción ->''')

        self.Label1_5 = Label(self.Frame1)
        self.Label1_5.place(relx=0.2, rely=0.04, height=23, width=157)
        self.Label1_5.configure(activebackground="#ffffff")
        self.Label1_5.configure(background="#ffffff")
        self.Label1_5.configure(font=font9)
        self.Label1_5.configure(text='''Monitorización''')

        self.D_eje_y = Label(self.Frame1)
        self.D_eje_y.place(relx=0.56, rely=0.18, height=23, width=87)
        self.D_eje_y.configure(activebackground="#ffffff")
        self.D_eje_y.configure(background="#ffffff")
        self.D_eje_y.configure(font=font11)
        self.D_eje_y.configure(justify=LEFT)
        self.D_eje_y.configure(text='''D_eje_y''')

        self.D_eje_x = Label(self.Frame1)
        self.D_eje_x.place(relx=0.56, rely=0.31, height=23, width=87)
        self.D_eje_x.configure(activebackground="#ffffff")
        self.D_eje_x.configure(background="#ffffff")
        self.D_eje_x.configure(font=font11)
        self.D_eje_x.configure(justify=LEFT)
        self.D_eje_x.configure(text='''D_eje_x''')

        self.Temp_C1 = Label(self.Frame1)
        self.Temp_C1.place(relx=0.59, rely=0.44, height=23, width=87)
        self.Temp_C1.configure(activebackground="#ffffff")
        self.Temp_C1.configure(background="#ffffff")
        self.Temp_C1.configure(font=font11)
        self.Temp_C1.configure(justify=LEFT)
        self.Temp_C1.configure(text='''Temp_C1''')

        self.Temp_C2 = Label(self.Frame1)
        self.Temp_C2.place(relx=0.59, rely=0.58, height=23, width=87)
        self.Temp_C2.configure(activebackground="#ffffff")
        self.Temp_C2.configure(background="#ffffff")
        self.Temp_C2.configure(font=font11)
        self.Temp_C2.configure(justify=LEFT)
        self.Temp_C2.configure(text='''Temp_C2''')

        self.Vel_angular = Label(self.Frame1)
        self.Vel_angular.place(relx=0.62, rely=0.71, height=23, width=107)
        self.Vel_angular.configure(activebackground="#ffffff")
        self.Vel_angular.configure(background="#ffffff")
        self.Vel_angular.configure(font=font11)
        self.Vel_angular.configure(justify=LEFT)
        self.Vel_angular.configure(text='''Vel_angular''')

        self.Vel_trac = Label(self.Frame1)
        self.Vel_trac.place(relx=0.69, rely=0.84, height=23, width=87)
        self.Vel_trac.configure(activebackground="#ffffff")
        self.Vel_trac.configure(background="#ffffff")
        self.Vel_trac.configure(font=font11)
        self.Vel_trac.configure(justify=LEFT)
        self.Vel_trac.configure(text='''Vel_trac''')

        self.D_eje_y_12 = Label(self.Frame1)
        self.D_eje_y_12.place(relx=1.43, rely=1.12, height=23, width=87)
        self.D_eje_y_12.configure(activebackground="#ffffff")
        self.D_eje_y_12.configure(background="#ffffff")
        self.D_eje_y_12.configure(font=font10)
        self.D_eje_y_12.configure(justify=LEFT)
        self.D_eje_y_12.configure(text='''D_eje_y''')

        self.Button1 = Button(top)
        self.Button1.place(relx=0.85, rely=0.83, height=27, width=86)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Comenzar''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.52, rely=0.83, height=27, width=109)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''Configuración''')

        self.Button3 = Button(top)
        self.Button3.place(relx=0.7, rely=0.83, height=27, width=94)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(text='''Precalentar''')

        self.Button4 = Button(top)
        self.Button4.place(relx=0.74, rely=0.0, height=112, width=162)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(background="#ffffff")
        self.Button4.configure(borderwidth="0")
        self.Button4.configure(disabledforeground="#ffffff")
        self.Button4.configure(highlightbackground="#ffffff")
        self._img1 = PhotoImage(file="../../GUI/Logos/SARGO_Pro.png")
        self.Button4.configure(image=self._img1)
        self.Button4.configure(relief=FLAT)
        self.Button4.configure(textvariable=GUI_Design_support.Proyecto_SARGO)

        self.Frame1_13 = Frame(top)
        self.Frame1_13.place(relx=0.52, rely=0.26, relheight=0.54, relwidth=0.45)

        self.Frame1_13.configure(relief=RIDGE)
        self.Frame1_13.configure(borderwidth="2")
        self.Frame1_13.configure(relief=RIDGE)
        self.Frame1_13.configure(background="#ffffff")
        self.Frame1_13.configure(width=305)

        self.Label1_14 = Label(self.Frame1_13)
        self.Label1_14.place(relx=0.03, rely=0.18, height=23, width=158)
        self.Label1_14.configure(activebackground="#ffffff")
        self.Label1_14.configure(background="#ffffff")
        self.Label1_14.configure(font=font10)
        self.Label1_14.configure(text='''Diámetro medio ->''')

        self.Label1_3 = Label(self.Frame1_13)
        self.Label1_3.place(relx=0.03, rely=0.31, height=23, width=97)
        self.Label1_3.configure(activebackground="#ffffff")
        self.Label1_3.configure(background="#ffffff")
        self.Label1_3.configure(font=font10)
        self.Label1_3.configure(text='''Ovalidad ->''')

        self.Label1_4 = Label(self.Frame1_13)
        self.Label1_4.place(relx=0.03, rely=0.44, height=23, width=157)
        self.Label1_4.configure(activebackground="#ffffff")
        self.Label1_4.configure(background="#ffffff")
        self.Label1_4.configure(font=font10)
        self.Label1_4.configure(text='''Gradiente Temp ->''')

        self.Label1_5 = Label(self.Frame1_13)
        self.Label1_5.place(relx=0.03, rely=0.58, height=23, width=157)
        self.Label1_5.configure(activebackground="#ffffff")
        self.Label1_5.configure(background="#ffffff")
        self.Label1_5.configure(font=font10)
        self.Label1_5.configure(text='''Metros filameto ->''')

        self.Label1_6 = Label(self.Frame1_13)
        self.Label1_6.place(relx=0.03, rely=0.71, height=23, width=167)
        self.Label1_6.configure(activebackground="#ffffff")
        self.Label1_6.configure(background="#ffffff")
        self.Label1_6.configure(font=font10)
        self.Label1_6.configure(text='''Velocidad media ->''')

        self.Label1_7 = Label(self.Frame1_13)
        self.Label1_7.place(relx=0.03, rely=0.84, height=23, width=157)
        self.Label1_7.configure(activebackground="#ffffff")
        self.Label1_7.configure(background="#ffffff")
        self.Label1_7.configure(font=font10)
        self.Label1_7.configure(text='''Densidad media ->''')

        self.Label1_6 = Label(self.Frame1_13)
        self.Label1_6.place(relx=0.2, rely=0.04, height=23, width=157)
        self.Label1_6.configure(activebackground="#ffffff")
        self.Label1_6.configure(background="#ffffff")
        self.Label1_6.configure(font=font9)
        self.Label1_6.configure(text='''Estadísticas''')

        self.D_medio = Label(self.Frame1_13)
        self.D_medio.place(relx=0.56, rely=0.18, height=23, width=87)
        self.D_medio.configure(activebackground="#ffffff")
        self.D_medio.configure(background="#ffffff")
        self.D_medio.configure(font=font11)
        self.D_medio.configure(justify=LEFT)
        self.D_medio.configure(text='''D_medio''')

        self.D_ovalidad = Label(self.Frame1_13)
        self.D_ovalidad.place(relx=0.39, rely=0.31, height=23, width=97)
        self.D_ovalidad.configure(activebackground="#ffffff")
        self.D_ovalidad.configure(background="#ffffff")
        self.D_ovalidad.configure(font=font11)
        self.D_ovalidad.configure(justify=LEFT)
        self.D_ovalidad.configure(text='''D_ovalidad''')

        self.Temp_grad = Label(self.Frame1_13)
        self.Temp_grad.place(relx=0.59, rely=0.44, height=23, width=97)
        self.Temp_grad.configure(activebackground="#ffffff")
        self.Temp_grad.configure(background="#ffffff")
        self.Temp_grad.configure(font=font11)
        self.Temp_grad.configure(justify=LEFT)
        self.Temp_grad.configure(text='''Temp_grad''')

        self.Metros_fil = Label(self.Frame1_13)
        self.Metros_fil.place(relx=0.59, rely=0.58, height=23, width=87)
        self.Metros_fil.configure(activebackground="#ffffff")
        self.Metros_fil.configure(background="#ffffff")
        self.Metros_fil.configure(font=font11)
        self.Metros_fil.configure(justify=LEFT)
        self.Metros_fil.configure(text='''Metros_fil''')

        self.Vel_angular_med = Label(self.Frame1_13)
        self.Vel_angular_med.place(relx=0.59, rely=0.71, height=23, width=97)
        self.Vel_angular_med.configure(activebackground="#ffffff")
        self.Vel_angular_med.configure(background="#ffffff")
        self.Vel_angular_med.configure(font=font11)
        self.Vel_angular_med.configure(justify=LEFT)
        self.Vel_angular_med.configure(text='''Vel_med''')

        self.Den_media = Label(self.Frame1_13)
        self.Den_media.place(relx=0.59, rely=0.84, height=23, width=97)
        self.Den_media.configure(activebackground="#ffffff")
        self.Den_media.configure(background="#ffffff")
        self.Den_media.configure(font=font11)
        self.Den_media.configure(justify=LEFT)
        self.Den_media.configure(text='''Den_media''')

        self.Dejey_13 = Label(self.Frame1_13)
        self.Dejey_13.place(relx=1.43, rely=1.12, height=23, width=87)
        self.Dejey_13.configure(activebackground="#ffffff")
        self.Dejey_13.configure(background="#ffffff")
        self.Dejey_13.configure(font=font10)
        self.Dejey_13.configure(justify=LEFT)
        self.Dejey_13.configure(text='''D_eje_y''')

        self.Entry_rutas = Entry(top)
        self.Entry_rutas.place(relx=0.4, rely=0.93,height=21, relwidth=0.57)
        self.Entry_rutas.configure(background="white")
        self.Entry_rutas.configure(font="TkFixedFont")
        self.Entry_rutas.configure(selectbackground="#c4c4c4")

        self.Label1_6 = Label(top)
        self.Label1_6.place(relx=0.03, rely=0.05, height=23, width=77)
        self.Label1_6.configure(activebackground="#ffffff")
        self.Label1_6.configure(background="#ffffff")
        self.Label1_6.configure(font=font11)
        self.Label1_6.configure(text='''Fecha:''')

        self.Label1_7 = Label(top)
        self.Label1_7.place(relx=0.03, rely=0.93, height=23, width=247)
        self.Label1_7.configure(activebackground="#ffffff")
        self.Label1_7.configure(background="#ffffff")
        self.Label1_7.configure(font=font12)
        self.Label1_7.configure(text='''Ubicación de las estadísticas:''')
        self.Label1_7.configure(width=247)

        self.Label1_7 = Label(top)
        self.Label1_7.place(relx=0.03, rely=0.1, height=23, width=77)
        self.Label1_7.configure(activebackground="#ffffff")
        self.Label1_7.configure(background="#ffffff")
        self.Label1_7.configure(font=font11)
        self.Label1_7.configure(text='''Hora:''')

        self.Label_fecha = Label(top)
        self.Label_fecha.place(relx=0.13, rely=0.05, height=23, width=127)
        self.Label_fecha.configure(activebackground="#ffffff")
        self.Label_fecha.configure(background="#ffffff")
        self.Label_fecha.configure(font=font10)
        self.Label_fecha.configure(text='''14/08/2018''')

        self.Label_hora = Label(top)
        self.Label_hora.place(relx=0.13, rely=0.1, height=23, width=127)
        self.Label_hora.configure(activebackground="#ffffff")
        self.Label_hora.configure(background="#ffffff")
        self.Label_hora.configure(font=font10)
        self.Label_hora.configure(text='''18:51''')

        # Llamamos a las funciones que serán actualizadas durante la ejecución
        self.updateClock()
        self.updateDate()
        self.updateDiameterAxisY()

    def updateClock(self):
        # Guardamos la hora actual
        hora = "%s" %time.strftime("%H:%M:%S")
        ## Actualizamos el valor del reloj mostrado
        self.Label_hora.configure(text=hora)
        # Repetimos la llamada
        self.top.after(self.TimerInterval,self.updateClock)

    def updateDate(self):
        # Guardamos la fecha actual
        fecha = "%s" %time.strftime("%m/%d/%Y")
        ## Actualizamos el valor del calendario mostrado
        self.Label_fecha.configure(text=fecha)
        # Repetimos la llamada
        self.top.after(self.TimerInterval,self.updateDate)

    def updateDiameterAxisY(self):
        # Generamos un valor aleatorio para realizar el test
        self.diameterAxisY = random.randint(1,10)
        # Actualizamos el valor mostrado
        self.D_eje_y.configure(text=str(self.diameterAxisY))
        # Repetimos la llamada a la función
        self.top.after(self.TimerInterval,self.updateDiameterAxisY)



if __name__ == '__main__':
    vp_start_gui()
